version: "3.8"

services:
  # Backend Nodejs Service
  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "4000:3000"
    networks:
      - backend
    # volumes:
    #   - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - ngrok
      - bot-setup
    env_file:
      - .env

  # Telegram Bot Webhook Setup service
  bot-setup:
    build: ./bot-setup
    container_name: bot-setup
    networks:
      - backend
    depends_on:
      - db
      - ngrok
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NGROK_TUNNEL=${NGROK_TUNNEL}
    env_file:
      - .env
    restart: on-failure

  # Next.js Service
  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    networks:
      - backend
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    env_file:
      - .env
    command: npm run dev
    stdin_open: true
    tty: true

  # Ngrok Service
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PORT=backend:3000
    ports:
      - "4040:4040"
    networks:
      - backend

  # Postgress DB

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5555:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data


  test-db:
    image: postgres:14
    container_name: postgres-test-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5556:5432"
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  pgdata:
